# Template to create an ec2 instance that uses exported Values from SampleNetwork.yml
Mappings:
  RegionSelect:
    us-west-2:
      Linux: "ami-03c7c1f17ee073747"
    us-east-1:
      Linux: "ami-0bef6cc322bfff646" 

Resources:     
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !FindInMap [RegionSelect, !Ref "AWS::Region", Linux] 
      KeyName: 'G3test' # replace with own key 
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
          - !ImportValue SampleNetworkCross-Stack-SecurityGroupID
        SubnetId: 
          !ImportValue SampleNetworkCross-Stack-SubnetID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Ec2 launch by Guillaume through CloudFormation with exported SampleNetworkCrossStack" > /var/www/html/index.html

  MyIPaddress:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref Ec2Instance

Outputs:
  Ec2PrivateIP:
    Description: "To retrieve and display IP address in outputs section"
    Value: !GetAtt Ec2Instance.PublicIp
  MyEC2DnsName:
    Description: "To display DNS name in outputs section"
    Value: !GetAtt Ec2Instance.PublicDnsName 

Parameters:
  InstanceType:
    Description: Choose Ec2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small 
    ConstraintDescription: 'must be a valid Ec2 instance type'       





      


      

       
     
      
      
      
      
      
      
      
      
